# Generated by Django 5.0.4 on 2024-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersaccepted',
            name='acceptedTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersaccepted',
            name='expectedDeliveryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
