# Generated by Django 5.0.4 on 2024-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cost',
            field=models.FloatField(default=30.0),
        ),
    ]
