# Generated by Django 5.0.4 on 2024-05-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_route_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.route'),
        ),
    ]
