# Generated by Django 5.0.4 on 2024-05-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraccount_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.route'),
        ),
    ]
