# Generated by Django 5.0.4 on 2024-05-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_useraccount_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.route'),
        ),
    ]
